#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Escuela")]
public partial class Data_EscuelaDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Definiciones de métodos de extensibilidad
  partial void OnCreated();
  #endregion
	
	public Data_EscuelaDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["EscuelaConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public Data_EscuelaDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public Data_EscuelaDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public Data_EscuelaDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public Data_EscuelaDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<tbl_SicoPractico> tbl_SicoPractico
	{
		get
		{
			return this.GetTable<tbl_SicoPractico>();
		}
	}
	
	public System.Data.Linq.Table<tmpAutosUtilizados15QTE> tmpAutosUtilizados15QTE
	{
		get
		{
			return this.GetTable<tmpAutosUtilizados15QTE>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_SicoPractico")]
public partial class tbl_SicoPractico
{
	
	private int _id_SicoPractico;
	
	private string _sucursal;
	
	private System.Nullable<int> _numero;
	
	private string _tipoDocumento;
	
	private string _cedula;
	
	private string _factura;
	
	private System.Nullable<System.DateTime> _fecha;
	
	private System.Nullable<System.DateTime> _fechaSicotecnico;
	
	private System.Nullable<System.DateTime> _fechaPractico;
	
	private System.Nullable<decimal> _notaPractico;
	
	private string _estadoPsico;
	
	private string _instructorEvaluador;
	
	private string _resultado;
	
	private string _elaborado;
	
	private string _iniciales;
	
	private string _oficio;
	
	private string _observacion;
	
	private string _directorEscuela;
	
	private string _responsablePractico;
	
	private string _responsablePsico;
	
	public tbl_SicoPractico()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_SicoPractico", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
	public int id_SicoPractico
	{
		get
		{
			return this._id_SicoPractico;
		}
		set
		{
			if ((this._id_SicoPractico != value))
			{
				this._id_SicoPractico = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sucursal", DbType="VarChar(3)")]
	public string sucursal
	{
		get
		{
			return this._sucursal;
		}
		set
		{
			if ((this._sucursal != value))
			{
				this._sucursal = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numero", DbType="Int")]
	public System.Nullable<int> numero
	{
		get
		{
			return this._numero;
		}
		set
		{
			if ((this._numero != value))
			{
				this._numero = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipoDocumento", DbType="VarChar(1)")]
	public string tipoDocumento
	{
		get
		{
			return this._tipoDocumento;
		}
		set
		{
			if ((this._tipoDocumento != value))
			{
				this._tipoDocumento = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cedula", DbType="VarChar(15)")]
	public string cedula
	{
		get
		{
			return this._cedula;
		}
		set
		{
			if ((this._cedula != value))
			{
				this._cedula = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_factura", DbType="VarChar(15)")]
	public string factura
	{
		get
		{
			return this._factura;
		}
		set
		{
			if ((this._factura != value))
			{
				this._factura = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha", DbType="DateTime")]
	public System.Nullable<System.DateTime> fecha
	{
		get
		{
			return this._fecha;
		}
		set
		{
			if ((this._fecha != value))
			{
				this._fecha = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaSicotecnico", DbType="DateTime")]
	public System.Nullable<System.DateTime> fechaSicotecnico
	{
		get
		{
			return this._fechaSicotecnico;
		}
		set
		{
			if ((this._fechaSicotecnico != value))
			{
				this._fechaSicotecnico = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaPractico", DbType="DateTime")]
	public System.Nullable<System.DateTime> fechaPractico
	{
		get
		{
			return this._fechaPractico;
		}
		set
		{
			if ((this._fechaPractico != value))
			{
				this._fechaPractico = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_notaPractico", DbType="Decimal(18,2)")]
	public System.Nullable<decimal> notaPractico
	{
		get
		{
			return this._notaPractico;
		}
		set
		{
			if ((this._notaPractico != value))
			{
				this._notaPractico = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estadoPsico", DbType="VarChar(1)")]
	public string estadoPsico
	{
		get
		{
			return this._estadoPsico;
		}
		set
		{
			if ((this._estadoPsico != value))
			{
				this._estadoPsico = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_instructorEvaluador", DbType="Text", UpdateCheck=UpdateCheck.Never)]
	public string instructorEvaluador
	{
		get
		{
			return this._instructorEvaluador;
		}
		set
		{
			if ((this._instructorEvaluador != value))
			{
				this._instructorEvaluador = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_resultado", DbType="VarChar(1)")]
	public string resultado
	{
		get
		{
			return this._resultado;
		}
		set
		{
			if ((this._resultado != value))
			{
				this._resultado = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_elaborado", DbType="Text", UpdateCheck=UpdateCheck.Never)]
	public string elaborado
	{
		get
		{
			return this._elaborado;
		}
		set
		{
			if ((this._elaborado != value))
			{
				this._elaborado = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iniciales", DbType="VarChar(10)")]
	public string iniciales
	{
		get
		{
			return this._iniciales;
		}
		set
		{
			if ((this._iniciales != value))
			{
				this._iniciales = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_oficio", DbType="VarChar(15)")]
	public string oficio
	{
		get
		{
			return this._oficio;
		}
		set
		{
			if ((this._oficio != value))
			{
				this._oficio = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_observacion", DbType="Text", UpdateCheck=UpdateCheck.Never)]
	public string observacion
	{
		get
		{
			return this._observacion;
		}
		set
		{
			if ((this._observacion != value))
			{
				this._observacion = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_directorEscuela", DbType="Text", UpdateCheck=UpdateCheck.Never)]
	public string directorEscuela
	{
		get
		{
			return this._directorEscuela;
		}
		set
		{
			if ((this._directorEscuela != value))
			{
				this._directorEscuela = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_responsablePractico", DbType="Text", UpdateCheck=UpdateCheck.Never)]
	public string responsablePractico
	{
		get
		{
			return this._responsablePractico;
		}
		set
		{
			if ((this._responsablePractico != value))
			{
				this._responsablePractico = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_responsablePsico", DbType="Text", UpdateCheck=UpdateCheck.Never)]
	public string responsablePsico
	{
		get
		{
			return this._responsablePsico;
		}
		set
		{
			if ((this._responsablePsico != value))
			{
				this._responsablePsico = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tmpAutosUtilizados15QTE")]
public partial class tmpAutosUtilizados15QTE
{
	
	private System.Nullable<int> _VEH_ID;
	
	private string @__06_00;
	
	private string @__07_00;
	
	private string @__08_00;
	
	private string @__09_00;
	
	private string @__10_00;
	
	private string @__11_00;
	
	private string @__12_00;
	
	private string @__13_00;
	
	private string @__14_30;
	
	private string @__16_00;
	
	private string @__17_00;
	
	private string @__18_00;
	
	private string @__19_00;
	
	private string @__20_00;
	
	private string @__21_00;
	
	public tmpAutosUtilizados15QTE()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VEH_ID", DbType="Int")]
	public System.Nullable<int> VEH_ID
	{
		get
		{
			return this._VEH_ID;
		}
		set
		{
			if ((this._VEH_ID != value))
			{
				this._VEH_ID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[06:00]", Storage="__06_00", DbType="VarChar(401)")]
	public string _06_00
	{
		get
		{
			return this.@__06_00;
		}
		set
		{
			if ((this.@__06_00 != value))
			{
				this.@__06_00 = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[07:00]", Storage="__07_00", DbType="VarChar(401)")]
	public string _07_00
	{
		get
		{
			return this.@__07_00;
		}
		set
		{
			if ((this.@__07_00 != value))
			{
				this.@__07_00 = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[08:00]", Storage="__08_00", DbType="VarChar(401)")]
	public string _08_00
	{
		get
		{
			return this.@__08_00;
		}
		set
		{
			if ((this.@__08_00 != value))
			{
				this.@__08_00 = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[09:00]", Storage="__09_00", DbType="VarChar(401)")]
	public string _09_00
	{
		get
		{
			return this.@__09_00;
		}
		set
		{
			if ((this.@__09_00 != value))
			{
				this.@__09_00 = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[10:00]", Storage="__10_00", DbType="VarChar(401)")]
	public string _10_00
	{
		get
		{
			return this.@__10_00;
		}
		set
		{
			if ((this.@__10_00 != value))
			{
				this.@__10_00 = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[11:00]", Storage="__11_00", DbType="VarChar(401)")]
	public string _11_00
	{
		get
		{
			return this.@__11_00;
		}
		set
		{
			if ((this.@__11_00 != value))
			{
				this.@__11_00 = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[12:00]", Storage="__12_00", DbType="VarChar(401)")]
	public string _12_00
	{
		get
		{
			return this.@__12_00;
		}
		set
		{
			if ((this.@__12_00 != value))
			{
				this.@__12_00 = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[13:00]", Storage="__13_00", DbType="VarChar(401)")]
	public string _13_00
	{
		get
		{
			return this.@__13_00;
		}
		set
		{
			if ((this.@__13_00 != value))
			{
				this.@__13_00 = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[14:30]", Storage="__14_30", DbType="VarChar(401)")]
	public string _14_30
	{
		get
		{
			return this.@__14_30;
		}
		set
		{
			if ((this.@__14_30 != value))
			{
				this.@__14_30 = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[16:00]", Storage="__16_00", DbType="VarChar(401)")]
	public string _16_00
	{
		get
		{
			return this.@__16_00;
		}
		set
		{
			if ((this.@__16_00 != value))
			{
				this.@__16_00 = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[17:00]", Storage="__17_00", DbType="VarChar(401)")]
	public string _17_00
	{
		get
		{
			return this.@__17_00;
		}
		set
		{
			if ((this.@__17_00 != value))
			{
				this.@__17_00 = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[18:00]", Storage="__18_00", DbType="VarChar(401)")]
	public string _18_00
	{
		get
		{
			return this.@__18_00;
		}
		set
		{
			if ((this.@__18_00 != value))
			{
				this.@__18_00 = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[19:00]", Storage="__19_00", DbType="VarChar(401)")]
	public string _19_00
	{
		get
		{
			return this.@__19_00;
		}
		set
		{
			if ((this.@__19_00 != value))
			{
				this.@__19_00 = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[20:00]", Storage="__20_00", DbType="VarChar(401)")]
	public string _20_00
	{
		get
		{
			return this.@__20_00;
		}
		set
		{
			if ((this.@__20_00 != value))
			{
				this.@__20_00 = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[21:00]", Storage="__21_00", DbType="VarChar(401)")]
	public string _21_00
	{
		get
		{
			return this.@__21_00;
		}
		set
		{
			if ((this.@__21_00 != value))
			{
				this.@__21_00 = value;
			}
		}
	}
}
#pragma warning restore 1591
